site_name: 2024.1 - SINDPOL
site_url: 'https://documentacao-SINDPOL.com/'

repo_name: '2024.1 - SINDPOL'
repo_url: 'https://github.com/fga-eps-mds/2024.1-SINDPOL-DOC'

theme:
  name: material
  palette:
    primary: orange
    secondary: red
  # logo:
  # favicon:

plugins:
  - search

nav:
  - Sobre: index.md
  - Alinhamento da equipe: 
    - Canais de comunicação: alinhamento/canais.md
    - Planejamento de dojos: alinhamento/dojos.md
    - Quadro de disponibilidade: alinhamento/disponibilidade.md
    - Quadro de conhecimento: alinhamento/heatmap.md
