site_name: 2024.1 - SINDPOL
site_url: 'https://documentacao-SINDPOL.com/'

repo_name: '2024.1 - SINDPOL'
repo_url: 'https://github.com/fga-eps-mds/2024.1-SINDPOL-DOC'

theme:
  name: material
  palette:
    primary: orange
    secondary: red
  # logo:
  # favicon:

plugins:
  - search

nav:
  - Home: index.md
  - Documentação:
    - Home: home.md
  - Sprints:
    - Sprint 0:
      - Review: sprints/sprint0/sprint0_review.md
      - Planning: sprints/sprint0/sprint0_planning.md
  - About: about.md